version: '3.7'
services:
  frontend:
    build:
      context: ./front 
      dockerfile: Dockerfile
    ports:   
    - "8080:80"
backend:
  build:
    context: ./back
    dockerfile: Dockerfile
  ports:
  - "3000:3000"
